//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSaladin.SpeedTime.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpeedTime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpeedTime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSaladin.SpeedTime.Language.SpeedTime", typeof(SpeedTime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic pause detection.
        /// </summary>
        public static string automatic_pause {
            get {
                return ResourceManager.GetString("automatic-pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFK.
        /// </summary>
        public static string quicktimetracker_afk {
            get {
                return ResourceManager.GetString("quicktimetracker.afk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string quicktimetracker_break {
            get {
                return ResourceManager.GetString("quicktimetracker.break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Entry: {0}.
        /// </summary>
        public static string quicktimetracker_last_entry {
            get {
                return ResourceManager.GetString("quicktimetracker.last-entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of your work.
        /// </summary>
        public static string quicktimetracker_placeholder {
            get {
                return ResourceManager.GetString("quicktimetracker.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto add break on lock.
        /// </summary>
        public static string settings_auto_break {
            get {
                return ResourceManager.GetString("settings.auto-break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string settings_behavior_title {
            get {
                return ResourceManager.GetString("settings.behavior.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string settings_integrations_title {
            get {
                return ResourceManager.GetString("settings.integrations.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Links.
        /// </summary>
        public static string settings_task_linking {
            get {
                return ResourceManager.GetString("settings.task-linking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings_title {
            get {
                return ResourceManager.GetString("settings.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string settings_ui_accent {
            get {
                return ResourceManager.GetString("settings.ui-accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Language.
        /// </summary>
        public static string settings_ui_language {
            get {
                return ResourceManager.GetString("settings.ui-language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string settings_ui_theme {
            get {
                return ResourceManager.GetString("settings.ui-theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string settings_ui_title {
            get {
                return ResourceManager.GetString("settings.ui.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Work Hours.
        /// </summary>
        public static string settings_weekly_hour {
            get {
                return ResourceManager.GetString("settings.weekly-hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workdays.
        /// </summary>
        public static string settings_workdays {
            get {
                return ResourceManager.GetString("settings.workdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month - Daily.
        /// </summary>
        public static string statistics_grouping_month_daily {
            get {
                return ResourceManager.GetString("statistics.grouping.month-daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month - Weekly.
        /// </summary>
        public static string statistics_grouping_month_weekly {
            get {
                return ResourceManager.GetString("statistics.grouping.month-weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week - Daily.
        /// </summary>
        public static string statistics_grouping_week_daily {
            get {
                return ResourceManager.GetString("statistics.grouping.week-daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string statistics_legends_actual {
            get {
                return ResourceManager.GetString("statistics.legends.actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string statistics_legends_target {
            get {
                return ResourceManager.GetString("statistics.legends.target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string statistics_title {
            get {
                return ResourceManager.GetString("statistics.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week {0}.
        /// </summary>
        public static string statistics_week_placeholder {
            get {
                return ResourceManager.GetString("statistics.week-placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Prefix.
        /// </summary>
        public static string tasklinkeditor_check_placeholder {
            get {
                return ResourceManager.GetString("tasklinkeditor.check-placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Link ({0} for ID Placeholder).
        /// </summary>
        public static string tasklinkeditor_link_placeholder {
            get {
                return ResourceManager.GetString("tasklinkeditor.link-placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Link.
        /// </summary>
        public static string tasklinkeditor_title {
            get {
                return ResourceManager.GetString("tasklinkeditor.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Links.
        /// </summary>
        public static string tasklinking_title {
            get {
                return ResourceManager.GetString("tasklinking.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string timeeditor_break {
            get {
                return ResourceManager.GetString("timeeditor.break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Editor.
        /// </summary>
        public static string timeeditor_title {
            get {
                return ResourceManager.GetString("timeeditor.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy.
        /// </summary>
        public static string times_current_date_format {
            get {
                return ResourceManager.GetString("times.current-date-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0:N2}h.
        /// </summary>
        public static string times_current_hours {
            get {
                return ResourceManager.GetString("times.current.hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: {0}.
        /// </summary>
        public static string times_current_title {
            get {
                return ResourceManager.GetString("times.current.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is free Day.
        /// </summary>
        public static string times_date_is_free_day {
            get {
                return ResourceManager.GetString("times.date.is-free-day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string times_totals_title {
            get {
                return ResourceManager.GetString("times.totals.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nah.
        /// </summary>
        public static string updateapp_cancel {
            get {
                return ResourceManager.GetString("updateapp.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string updateapp_download {
            get {
                return ResourceManager.GetString("updateapp.download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, dd. MMMM yyyy.
        /// </summary>
        public static string updateapp_release_date_format {
            get {
                return ResourceManager.GetString("updateapp.release-date-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available!.
        /// </summary>
        public static string updateapp_title {
            get {
                return ResourceManager.GetString("updateapp.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released on: {0}..
        /// </summary>
        public static string updateapp_version_release_date {
            get {
                return ResourceManager.GetString("updateapp.version-release-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version {0} is available to download..
        /// </summary>
        public static string updateapp_version_text {
            get {
                return ResourceManager.GetString("updateapp.version-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workdays.
        /// </summary>
        public static string workdays_title {
            get {
                return ResourceManager.GetString("workdays.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string workdays_total_hours {
            get {
                return ResourceManager.GetString("workdays.total-hours", resourceCulture);
            }
        }
    }
}
